version: '3.7'

volumes:
  maven-repository: 
  application:

services:

  petclinic:
    build:
      context: _application
      dockerfile: Dockerfile    
    image: spring-petclinic
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - "application:/app"
      - "maven-repository:/root/.m2/repository"

  firefly-desktop:
    image: "weaveworld/firefly-desktop"  
    ports:
      - 7900:7900
      - 4444:4444
      - 7777:7777
    command: [ "firefly", "-s", "/app", "-o", "/home/app/result", "-i", "-p", "7777", "BROWSER=chrome:4444", "APP_URL=http://petclinic:8080" ]
    volumes:
      - ./:/app
      - ./result:/home/app/result
