version: '3.7'
#
# Testing with weaveworld/selenium docker image
#

volumes:
  maven-repository: 
  application:

services:

  petclinic:
    build:
      context: _application
      dockerfile: Dockerfile    
    image: spring-petclinic
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - "application:/app"
      - "maven-repository:/root/.m2/repository"

  selenium:
    image: weaveworld/selenium
    ports:
      - 7900:7900 
      - 4444:4444 
    shm_size: 2gb

  firefly:
    image: "weaveworld/firefly"  
    ports:
      - 7777:7777
    entrypoint: [ "firefly", "APP_URL=http://petclinic:8080", "BROWSER=chrome:4444", "-p", "7777" ]
    command: [ "-s", "/app", "-o", "/home/app/result", "-i", ]
    volumes:
      - ./:/app
      - ./result:/home/app/result      